# Generated by Django 3.1.4 on 2020-12-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_question_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice3',
        ),
    ]
